-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.conversation_summaries
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    conversation_id uuid NOT NULL,
    summary text COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT conversation_summaries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.conversations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    scenario_id uuid NOT NULL,
    scenario_role_id uuid NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    started_at timestamp without time zone NOT NULL DEFAULT now(),
    ended_at timestamp without time zone,
    CONSTRAINT conversations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.feedback_sessions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    conversation_id uuid NOT NULL,
    overall_feedback text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT feedback_sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.message_feedback
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    feedback_session_id uuid NOT NULL,
    message_id uuid NOT NULL,
    original_text text COLLATE pg_catalog."default" NOT NULL,
    corrected_text text COLLATE pg_catalog."default" NOT NULL,
    mistakes jsonb NOT NULL DEFAULT '[]'::jsonb,
    better_alternatives jsonb NOT NULL DEFAULT '[]'::jsonb,
    explanations jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT message_feedback_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    conversation_id uuid NOT NULL,
    sender character varying(10) COLLATE pg_catalog."default" NOT NULL,
    message_type character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'text'::character varying,
    content text COLLATE pg_catalog."default" NOT NULL,
    transcript text COLLATE pg_catalog."default",
    audio_url text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scenario_roles
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    scenario_id uuid NOT NULL,
    role_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    prompt_context text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT scenario_roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.scenarios
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    prompt_context text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    is_premium boolean NOT NULL DEFAULT false,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT scenarios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subscriptions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    provider character varying(50) COLLATE pg_catalog."default" NOT NULL,
    provider_subscription_id text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    current_period_end timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_profiles
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    common_mistakes jsonb NOT NULL DEFAULT '[]'::jsonb,
    grammar_focus_areas jsonb NOT NULL DEFAULT '[]'::jsonb,
    vocabulary_gaps jsonb NOT NULL DEFAULT '[]'::jsonb,
    strengths jsonb NOT NULL DEFAULT '[]'::jsonb,
    last_feedback_summary text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT user_profiles_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    plan character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'free'::character varying,
    german_level character varying(10) COLLATE pg_catalog."default",
    native_language character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.conversation_summaries
    ADD CONSTRAINT conversation_summaries_conversation_id_fkey FOREIGN KEY (conversation_id)
    REFERENCES public.conversations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uniq_conversation_summary
    ON public.conversation_summaries(conversation_id);


ALTER TABLE IF EXISTS public.conversations
    ADD CONSTRAINT conversations_scenario_id_fkey FOREIGN KEY (scenario_id)
    REFERENCES public.scenarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_conversations_scenario
    ON public.conversations(scenario_id);


ALTER TABLE IF EXISTS public.conversations
    ADD CONSTRAINT conversations_scenario_role_id_fkey FOREIGN KEY (scenario_role_id)
    REFERENCES public.scenario_roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_conversations_role
    ON public.conversations(scenario_role_id);


ALTER TABLE IF EXISTS public.conversations
    ADD CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_conversations_user
    ON public.conversations(user_id);


ALTER TABLE IF EXISTS public.feedback_sessions
    ADD CONSTRAINT feedback_sessions_conversation_id_fkey FOREIGN KEY (conversation_id)
    REFERENCES public.conversations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uniq_feedback_session
    ON public.feedback_sessions(conversation_id);


ALTER TABLE IF EXISTS public.message_feedback
    ADD CONSTRAINT message_feedback_feedback_session_id_fkey FOREIGN KEY (feedback_session_id)
    REFERENCES public.feedback_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_message_feedback_session
    ON public.message_feedback(feedback_session_id);


ALTER TABLE IF EXISTS public.message_feedback
    ADD CONSTRAINT message_feedback_message_id_fkey FOREIGN KEY (message_id)
    REFERENCES public.messages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uniq_message_feedback_message
    ON public.message_feedback(message_id);


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id)
    REFERENCES public.conversations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_messages_conversation
    ON public.messages(conversation_id);


ALTER TABLE IF EXISTS public.scenario_roles
    ADD CONSTRAINT scenario_roles_scenario_id_fkey FOREIGN KEY (scenario_id)
    REFERENCES public.scenarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_scenario_roles_scenario
    ON public.scenario_roles(scenario_id);


ALTER TABLE IF EXISTS public.subscriptions
    ADD CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_subscriptions_user
    ON public.subscriptions(user_id);


ALTER TABLE IF EXISTS public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uniq_user_profiles_user
    ON public.user_profiles(user_id);

END;
